apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx-ssh-portal.fullname" . }}
  labels:
    {{- include "nginx-ssh-portal.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{- .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: "{{ .Values.ingress.sharedSecretPrefix }}"
            pathType: Prefix
            backend:
              service:
                name: {{ include "nginx-ssh-portal.fullname" . }}
                port:
                  number: {{ .Values.ingress.httpPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx-ssh-portal.fullname" . }}-ssh
  labels:
    {{- include "nginx-ssh-portal.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    nginx.org/listen-ports: "{{ .Values.ingress.sshPort }}"
    nginx.org/server-snippets: |
        proxy_pass nginx-ssh-portal.svc.cluster.local:22;

spec: {}
